// form.js — provided for 8.01 Form Elements Lab
// Do not edit this file.
//
// When the volunteer sign-up form is submitted, this script:
//   1. Reads all the form values
//   2. Formats them into a readable email body
//   3. Opens the user's email app with the message pre-filled

document.getElementById('signup-form').addEventListener('submit', function (e) {
  e.preventDefault();

  // Read the text inputs
  let name = document.getElementById('volunteer-name').value.trim();
  let email = document.getElementById('volunteer-email').value.trim();

  // Read the selected radio button (program area)
  let programInput = document.querySelector('input[name="program"]:checked');
  let program = programInput ? programInput.value : '(none selected)';

  // Read all checked checkboxes (available days)
  let dayCheckboxes = document.querySelectorAll('input[name="days"]:checked');
  let days = [];
  dayCheckboxes.forEach(function (checkbox) {
    days.push(checkbox.value);
  });
  let daysText = days.length > 0 ? days.join(', ') : '(none selected)';

  // Read the textarea
  let notes = document.getElementById('notes').value.trim();

  // Validate that required fields are filled in
  if (!name || !email) {
    alert('Please fill in your name and email address before submitting.');
    return;
  }

  // Build the email body
  let body = [
    'Volunteer Sign-Up',
    'Name:          ' + name,
    'Email:         ' + email,
    'Program area:  ' + program,
    'Available days: ' + daysText,
    '',
    'Additional notes:',
    notes || '(none)',
  ].join('\n');

  // Build the mailto link and open it
  let subject = 'Volunteer Sign-Up: ' + name;
  let mailto = 'mailto:volunteer@greenvalleycc.org'
    + '?subject=' + encodeURIComponent(subject)
    + '&body=' + encodeURIComponent(body);

  window.location.href = mailto;
});
